"""
This type stub file was generated by pyright.
"""

class PiVideoStream:
	def __init__(self, resolution=..., framerate=..., **kwargs) -> None:
		...
	
	def start(self): # -> PiVideoStream:
		...
	
	def update(self): # -> None:
		...
	
	def read(self): # -> None:
		...
	
	def stop(self): # -> None:
		...
	


