"""
This type stub file was generated by pyright.
"""

from .iterative import *
from .minres import minres
from .lgmres import lgmres
from .lsqr import lsqr
from .lsmr import lsmr
from ._gcrotmk import gcrotmk
from scipy._lib._testutils import PytestTester

"Iterative Solvers for Sparse Linear Systems"
test = ...
