"""
This type stub file was generated by pyright.
"""

class WebcamVideoStream:
	def __init__(self, src=..., name=...) -> None:
		...
	
	def start(self): # -> WebcamVideoStream:
		...
	
	def update(self): # -> None:
		...
	
	def read(self):
		...
	
	def stop(self): # -> None:
		...
	


