"""
This type stub file was generated by pyright.
"""

""" Functions that operate on sparse matrices
"""
def estimate_blocksize(A, efficiency=...): # -> tuple[Literal[1], Literal[1]] | tuple[Literal[6], Literal[6]] | tuple[Literal[3], Literal[3]] | tuple[Literal[4], Literal[4]] | tuple[Literal[2], Literal[2]]:
    """Attempt to determine the blocksize of a sparse matrix

    Returns a blocksize=(r,c) such that
        - A.nnz / A.tobsr( (r,c) ).nnz > efficiency
    """
    ...

def count_blocks(A, blocksize):
    """For a given blocksize=(r,c) count the number of occupied
    blocks in a sparse matrix A
    """
    ...

