"""
This type stub file was generated by pyright.
"""

"""

Rules for building C/API module with f2py2e.

Copyright 1999,2000 Pearu Peterson all rights reserved,
Pearu Peterson <pearu@ioc.ee>
Permission to use, modify, and distribute this software is given under the
terms of the NumPy License.

NO WARRANTY IS EXPRESSED OR IMPLIED.  USE AT YOUR OWN RISK.
$Date: 2004/11/26 11:13:06 $
Pearu Peterson

"""
__version__ = ...
f2py_version = ...
def var2fixfortran(vars, a, fa=..., f90mode=...): # -> str:
    ...

def createfuncwrapper(rout, signature=...): # -> str:
    ...

def createsubrwrapper(rout, signature=...): # -> str:
    ...

def assubr(rout): # -> tuple[Unknown, str] | tuple[Unknown, Literal['']]:
    ...

