# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json

# Configuration file for https://pre-commit.com/
#
# Run `pre-commit install` once to install a Git pre-commit hook locally. This will
# ensure that each commit passes the checks before entering the Git history.

default_stages:
  # Prevent that hooks run twice, triggered by both
  # the Git commit-msg and the pre-commit hook.
- commit

# # See https://pre-commit.com for more information
# # See https://pre-commit.com/hooks.html for more hooks
# # NOTE: https://github.com/LouisdeBruijn/Medium/blob/master/.pre-commit-config.yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-ast
  - id: trailing-whitespace
  - id: check-toml
  - id: end-of-file-fixer

# - repo: https://github.com/asottile/add-trailing-comma
#   rev: v2.1.0
#   hooks:
#   - id: add-trailing-comma

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: pretty-format-yaml
    exclude: '^.*meta.yaml$'
    args:
    - --autofix
    - --preserve-quotes
    - --indent=2

# SOURCE: https://github.com/kartevonmorgen/openfairdb/commit/278adfdb5b376197028f98626177eef989eae7a9
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.4.0
  hooks:
  - id: commitlint
    stages:
    - commit-msg

- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.42.1
  hooks:
  - id: commitizen
    stages: [commit-msg]

# # - repo: https://github.com/sourcery-ai/sourcery
# #   rev: v1.0.5
# #   hooks:
# #   - id: sourcery
# #       # The best way to use Sourcery in a pre-commit hook:
# #       # * review only changed lines:
# #       # * omit the summary
# #     args: [--diff=git diff HEAD, --no-summary]

# # -   repo: https://github.com/charliermarsh/ruff-pre-commit
# #     rev: v0.0.252
# #     hooks:
# #     -   id: ruff
# #         args:
# #         - --fix

# # - repo: local
# #   hooks:
# #   - id: black
# #     name: Format with Black
# #     entry: black
# #     language: system
# #     types: [python]

# #   - id: autoflake
# #     name: autoflake
# #     entry: autoflake
# #     language: system
# #     types: [python]
# #     args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]

# #   - id: isort
# #     name: isort
# #     entry: isort
# #     language: system
# #     types: [python]

# #   - id: flake8
# #     name: Check with Flake8
# #     entry: flake8
# #     language: system
# #     pass_filenames: false
# #     types: [python]
# #     args: [--count, .]

# #   - id: mypy
# #     name: Validate types with MyPy
# #     entry: mypy
# #     language: system
# #     types: [python]
# #     pass_filenames: false
# #     args:
# #     - "dancedetector"
