"""
This type stub file was generated by pyright.
"""

class HARRIS:
    def __init__(self, blockSize=..., apertureSize=..., k=..., T=...) -> None:
        ...
    
    def detect(self, img): # -> list[Unknown]:
        ...
    


