"""
This type stub file was generated by pyright.
"""

"""

Build call-back mechanism for f2py2e.

Copyright 2000 Pearu Peterson all rights reserved,
Pearu Peterson <pearu@ioc.ee>
Permission to use, modify, and distribute this software is given under the
terms of the NumPy License.

NO WARRANTY IS EXPRESSED OR IMPLIED.  USE AT YOUR OWN RISK.
$Date: 2005/07/20 11:27:58 $
Pearu Peterson

"""
f2py_version = ...
cb_routine_rules = ...
cb_rout_rules = ...
cb_arg_rules = ...
cb_map = ...
def buildcallbacks(m): # -> None:
    ...

def buildcallback(rout, um): # -> None:
    ...

