"""
This type stub file was generated by pyright.
"""

from .auxfuncs import *

"""

Build F90 module support for f2py2e.

Copyright 2000 Pearu Peterson all rights reserved,
Pearu Peterson <pearu@ioc.ee>
Permission to use, modify, and distribute this software is given under the
terms of the NumPy License.

NO WARRANTY IS EXPRESSED OR IMPLIED.  USE AT YOUR OWN RISK.
$Date: 2005/02/03 19:30:23 $
Pearu Peterson

"""
__version__ = ...
f2py_version = ...
options = ...
def findf90modules(m): # -> list[Unknown]:
    ...

fgetdims1 = ...
fgetdims2 = ...
fgetdims2_sa = ...
def buildhooks(pymod): # -> tuple[dict[str, list[str] | dict[str, str]], str]:
    ...

