"""
This type stub file was generated by pyright.
"""

class VideoStream:
	def __init__(self, src=..., usePiCamera=..., resolution=..., framerate=..., **kwargs) -> None:
		...
	
	def start(self): # -> PiVideoStream | WebcamVideoStream:
		...
	
	def update(self): # -> None:
		...
	
	def read(self): # -> None:
		...
	
	def stop(self): # -> None:
		...
	


