"""
This type stub file was generated by pyright.
"""

from .arpack import *
from .lobpcg import *
from scipy._lib._testutils import PytestTester

"""
Sparse Eigenvalue Solvers
-------------------------

The submodules of sparse.linalg.eigen:
    1. lobpcg: Locally Optimal Block Preconditioned Conjugate Gradient Method

"""
test = ...
