"""
This type stub file was generated by pyright.
"""

import sys

if sys.version_info >= (3, 0):
	...
else:
	...
class FileVideoStream:
	def __init__(self, path, transform=..., queue_size=...) -> None:
		...
	
	def start(self): # -> FileVideoStream:
		...
	
	def update(self): # -> None:
		...
	
	def read(self):
		...
	
	def running(self): # -> bool:
		...
	
	def more(self): # -> bool:
		...
	
	def stop(self): # -> None:
		...
	


