#!/usr/bin/env bash

docker-compose -f hacking/docker-compose.yml build playground
docker-compose -f hacking/docker-compose.yml run -p 8089:8089 playground
# docker-compose -f hacking/docker-compose.yml down
