"""
This type stub file was generated by pyright.
"""

from distutils.command.build_clib import build_clib as old_build_clib

""" Modified version of build_clib that handles fortran source files.
"""
_l = old_build_clib.user_options
class build_clib(old_build_clib):
    description = ...
    user_options = ...
    boolean_options = ...
    def initialize_options(self): # -> None:
        ...
    
    def finalize_options(self): # -> None:
        ...
    
    def have_f_sources(self): # -> bool:
        ...
    
    def have_cxx_sources(self): # -> bool:
        ...
    
    def run(self): # -> None:
        ...
    
    def get_source_files(self): # -> list[Unknown]:
        ...
    
    def build_libraries(self, libraries): # -> None:
        ...
    
    def build_a_library(self, build_info, lib_name, libraries): # -> None:
        ...
    


