"""
This type stub file was generated by pyright.
"""

def has_column_major_storage(arr):
    ...

_type_conv = ...
def get_flinalg_funcs(names, arrays=..., debug=...): # -> tuple[Unknown, ...]:
    """Return optimal available _flinalg function objects with
    names. Arrays are used to determine optimal prefix."""
    ...

