"""
This type stub file was generated by pyright.
"""

def base64_encode_image(a): # -> str:
	...

def base64_decode_image(a): # -> Any:
	...

def base64_encode_array(a): # -> bytes:
	...

def base64_decode_array(a, dtype): # -> Any:
	...

