"""
This type stub file was generated by pyright.
"""

class FaceAligner:
	def __init__(self, predictor, desiredLeftEye=..., desiredFaceWidth=..., desiredFaceHeight=...) -> None:
		...
	
	def align(self, image, gray, rect): # -> Any:
		...
	


