"""
This type stub file was generated by pyright.
"""

from .rotation import Rotation, Slerp
from ._rotation_spline import RotationSpline
from scipy._lib._testutils import PytestTester

"""
Spatial Transformations (:mod:`scipy.spatial.transform`)
========================================================

.. currentmodule:: scipy.spatial.transform

This package implements various spatial transformations. For now,
only rotations are supported.

Rotations in 3 dimensions
-------------------------
.. autosummary::
   :toctree: generated/

   Rotation
   Slerp
   RotationSpline
"""
test = ...
