"""
This type stub file was generated by pyright.
"""

"""

Build 'use others module data' mechanism for f2py2e.

Unfinished.

Copyright 2000 Pearu Peterson all rights reserved,
Pearu Peterson <pearu@ioc.ee>
Permission to use, modify, and distribute this software is given under the
terms of the NumPy License.

NO WARRANTY IS EXPRESSED OR IMPLIED.  USE AT YOUR OWN RISK.
$Date: 2000/09/10 12:35:43 $
Pearu Peterson

"""
__version__ = ...
f2py_version = ...
usemodule_rules = ...
def buildusevars(m, r): # -> dict[Unknown, Unknown]:
    ...

def buildusevar(name, realname, vars, usemodulename): # -> dict[Unknown, Unknown]:
    ...

