#!/usr/bin/env bash

set -e
set -x

# pylint -E --rcfile=./lint-configs-python/python/.pylintrc
# pylint --disable=all --enable=F,E --rcfile ./lint-configs-python/python/pylintrc tweetpik_cli
# TODO: Re enable these guys 2/17/2021
flake8 tweetpik_cli --exclude=tweetpik_cli/db/migrations
mypy tweetpik_cli

black --check tweetpik_cli --diff
isort --recursive --check-only tweetpik_cli
