"""
This type stub file was generated by pyright.
"""

class DENSE:
    def __init__(self, step=..., radius=...) -> None:
        ...
    
    def detect(self, img): # -> list[Unknown]:
        ...
    
    def setInt(self, var, val): # -> None:
        ...
    


