"""
This type stub file was generated by pyright.
"""

class RootSIFT:
	def __init__(self) -> None:
		...
	
	def compute(self, image, kps, eps=...): # -> tuple[list[Unknown], None] | tuple[Any, NoseTester]:
		...
	


