"""
This type stub file was generated by pyright.
"""

def corners_to_keypoints(corners): # -> list[Unknown]:
    """function to take the corners from cv2.GoodFeaturesToTrack and return cv2.KeyPoints"""
    ...

