"""
This type stub file was generated by pyright.
"""

from scipy._lib._testutils import PytestTester

"""
Module containing private utility functions
===========================================

The ``scipy._lib`` namespace is empty (for now). Tests for all
utilities in submodules of ``_lib`` can be run with::

    from scipy import _lib
    _lib.test()

"""
test = ...
