"""
This type stub file was generated by pyright.
"""

"""Warnings and Exceptions that can be raised by special functions."""
class SpecialFunctionWarning(Warning):
    """Warning that can be emitted by special functions."""
    ...


class SpecialFunctionError(Exception):
    """Exception that can be raised by special functions."""
    ...


