"""
This type stub file was generated by pyright.
"""

from . import __version__

"""

Build common block mechanism for f2py2e.

Copyright 2000 Pearu Peterson all rights reserved,
Pearu Peterson <pearu@ioc.ee>
Permission to use, modify, and distribute this software is given under the
terms of the NumPy License

NO WARRANTY IS EXPRESSED OR IMPLIED.  USE AT YOUR OWN RISK.
$Date: 2005/05/06 10:57:33 $
Pearu Peterson

"""
__version__ = ...
f2py_version = ...
def findcommonblocks(block, top=...): # -> list[Unknown]:
    ...

def buildhooks(m): # -> tuple[dict[str, list[str]], str]:
    ...

