"""
This type stub file was generated by pyright.
"""

from . import __version__

"""

Rules for building C/API module with f2py2e.

Here is a skeleton of a new wrapper function (13Dec2001):

wrapper_function(args)
  declarations
  get_python_arguments, say, `a' and `b'

  get_a_from_python
  if (successful) {

    get_b_from_python
    if (successful) {

      callfortran
      if (successful) {

        put_a_to_python
        if (successful) {

          put_b_to_python
          if (successful) {

            buildvalue = ...

          }

        }

      }

    }
    cleanup_b

  }
  cleanup_a

  return buildvalue

Copyright 1999,2000 Pearu Peterson all rights reserved,
Pearu Peterson <pearu@ioc.ee>
Permission to use, modify, and distribute this software is given under the
terms of the NumPy License.

NO WARRANTY IS EXPRESSED OR IMPLIED.  USE AT YOUR OWN RISK.
$Date: 2005/08/30 08:58:42 $
Pearu Peterson

"""
__version__ = ...
f2py_version = ...
options = ...
sepdict = ...
generationtime = ...
module_rules = ...
defmod_rules = ...
routine_rules = ...
rout_rules = ...
typedef_need_dict = ...
aux_rules = ...
arg_rules = ...
check_rules = ...
def buildmodule(m, um): # -> dict[Unknown, Unknown]:
    """
    Return
    """
    ...

stnd = ...
def buildapi(rout): # -> tuple[dict[Unknown, Unknown], str]:
    ...

