"""
This type stub file was generated by pyright.
"""

def sort_contours(cnts, method=...): # -> tuple[Tuple[Unknown | Any], Tuple[Unknown | Any]]:
    ...

def label_contour(image, c, i, color=..., thickness=...):
    ...

