#!/usr/bin/env bash

set -e

isort --recursive  --force-single-line-importsaioscraperp tests
autoflake --recursive --remove-all-unused-imports --remove-unused-variables --in-place aioscraper tests
black aioscraper tests
isort --recursive aioscraper tests
