#!/usr/bin/env bash

set -e
set -x

# pylint -E --rcfile=./lint-configs-python/python/.pylintrc
# pylint --disable=all --enable=F,E --rcfile ./lint-configs-python/python/pylintrc aioscraper
# TODO: Re enable these guys 2/17/2021
flake8 aioscraper --exclude=aioscraper/db/migrations
mypy aioscraper

black --check aioscraper --diff
isort --recursive --check-only aioscraper
