"""
This type stub file was generated by pyright.
"""

"""
Generic test utilities.

"""
class FPUModeChangeWarning(RuntimeWarning):
    """Warning about FPU mode change"""
    ...


class PytestTester:
    """
    Pytest test runner entry point.
    """
    def __init__(self, module_name) -> None:
        ...
    
    def __call__(self, label=..., verbose=..., extra_argv=..., doctests=..., coverage=..., tests=..., parallel=...): # -> bool:
        ...
    


def check_free_memory(free_mb): # -> None:
    """
    Check *free_mb* of memory is available, otherwise do pytest.skip
    """
    ...

