"""
This type stub file was generated by pyright.
"""

def linear(r):
    ...

def thin_plate_spline(r): # -> float:
    ...

def cubic(r):
    ...

def quintic(r):
    ...

def multiquadric(r):
    ...

def inverse_multiquadric(r):
    ...

def inverse_quadratic(r):
    ...

def gaussian(r):
    ...

NAME_TO_FUNC = ...
def kernel_vector(x, y, kernel_func, out): # -> None:
    """Evaluate RBFs, with centers at `y`, at the point `x`."""
    ...

def polynomial_vector(x, powers, out): # -> None:
    """Evaluate monomials, with exponents from `powers`, at the point `x`."""
    ...

def kernel_matrix(x, kernel_func, out): # -> None:
    """Evaluate RBFs, with centers at `x`, at `x`."""
    ...

def polynomial_matrix(x, powers, out): # -> None:
    """Evaluate monomials, with exponents from `powers`, at `x`."""
    ...

