"""
This type stub file was generated by pyright.
"""

import os
import numpy as np
from ._fortran import *
from .system_info import combine_dict
from scipy._lib._testutils import PytestTester

numpy_nodepr_api = ...
def uses_blas64(): # -> bool:
    ...

def import_file(folder, module_name):
    """Import a file directly, avoiding importing scipy"""
    ...

test = ...
