"""
This type stub file was generated by pyright.
"""

"""distutils.command

Package containing implementation of all the standard Distutils
commands.

"""
def test_na_writable_attributes_deletion(): # -> None:
    ...

__revision__ = ...
distutils_all = ...
