#!/usr/bin/env bash

set -e
set -x

# pylint -E --rcfile=./lint-configs-python/python/.pylintrc
# pylint --disable=all --enable=F,E --rcfile ./lint-configs-python/python/pylintrc html_to_markdown_cli
# TODO: Re enable these guys 2/17/2021
flake8 html_to_markdown_cli --exclude=html_to_markdown_cli/db/migrations
mypy html_to_markdown_cli

black --check html_to_markdown_cli --diff
isort --recursive --check-only html_to_markdown_cli
