"""
This type stub file was generated by pyright.
"""

"""
This is only meant to add docs to objects defined in C-extension modules.
The purpose is to allow easier editing of the docstrings without
requiring a re-compile.

NOTE: Many of the methods of ndarray have corresponding functions.
      If you update these docstrings, please keep also the ones in
      core/fromnumeric.py, core/defmatrix.py up-to-date.

"""
def numeric_type_aliases(aliases): # -> list[tuple[Any, Unknown, Unknown]]:
    ...

possible_aliases = ...
def add_newdoc_for_scalar_type(obj, fixed_aliases, doc): # -> None:
    ...

